<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright © 2013 Sven Ruppert (sven.ruppert@gmail.com)

    Licensed under the EUPL-1.2.
    You may obtain a copy of the Licence at:

        https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>com.svenruppert</groupId>
    <artifactId>proxybuilder-parent</artifactId>
    <version>00.10.00</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>proxybuilder</artifactId>

  <name>Sven Ruppert ProxyBuilder</name>
  <description>Runtime proxy builders and annotation processors for generated static proxies.</description>
  <url>http://www.proxybuilder.org</url>

  <dependencies>
    <dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-annotations</artifactId>
      <version>4.9.8</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgument>-Xlint:all</compilerArgument>
          <compilerArgument>-proc:none</compilerArgument>
          <showWarnings>true</showWarnings>
          <showDeprecation>true</showDeprecation>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
