<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright © 2013 Sven Ruppert (sven.ruppert@gmail.com)

    Licensed under the EUPL-1.2.
    You may obtain a copy of the Licence at:

        https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

-->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.svenruppert</groupId>
    <artifactId>dependencies</artifactId>
    <version>06.02.01</version>
  </parent>

  <artifactId>proxybuilder-parent</artifactId>
  <version>00.11.01</version>

  <packaging>pom</packaging>
  <modules>
    <module>proxybuilder-annotations</module>
    <module>impl</module>
    <module>testusage</module>
  </modules>

  <inceptionYear>2013</inceptionYear>
  <organization>
    <name>jSentinel</name>
    <url>https://jsentinel.eu</url>
  </organization>
  <url>https://proxy.svenruppert.com</url>
  <name>ProxyBuilder</name>
  <description>Builder-Pattern for different types of proxies</description>

  <properties>
    <maven.compiler.release>26</maven.compiler.release>
    <maven.version>4.0.0-rc-5</maven.version>
    <maven.wrapper.version>3.3.4</maven.wrapper.version>
    <junit.version>6.0.2</junit.version>
    <maven.surefire.version>3.5.4</maven.surefire.version>
  </properties>

  <scm>
    <url>https://github.com/svenruppert/proxybuilder</url>
    <connection>scm:git:https://github.com/svenruppert/proxybuilder.git</connection>
    <developerConnection>scm:git:https://github.com/svenruppert/proxybuilder.git</developerConnection>
    <tag>HEAD</tag>
  </scm>
  <developers>
    <developer>
      <name>Sven Ruppert</name>
      <email>sven.ruppert@gmail.com</email>
      <roles>
        <role>Developer</role>
      </roles>
      <timezone>+1</timezone>
    </developer>
  </developers>
  <!--  <issueManagement>-->
  <!--    <system>Youtrack</system>-->
  <!--    <url>https://issues.rapidpm.org/issues?q=project%3A+ProxyBuilder</url>-->
  <!--  </issueManagement>-->
  <!--  <ciManagement>-->
  <!--    <system>TeamCity</system>-->
  <!--    <url>https://build.rapidpm.org/viewType.html?buildTypeId=RapidPM_Develop_ProxyBuilder_Snapshot</url>-->
  <!--  </ciManagement>-->
  <licenses>
    <license>
      <name>European Union Public Licence, Version 1.2</name>
      <url>https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12</url>
      <distribution>repo</distribution>
      <comments>SPDX identifier: EUPL-1.2</comments>
    </license>
  </licenses>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.svenruppert</groupId>
        <artifactId>proxybuilder-annotations</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.svenruppert</groupId>
        <artifactId>proxybuilder</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>


  <dependencies>
    <!--    APIs-->


    <dependency>
      <groupId>com.svenruppert</groupId>
      <artifactId>core</artifactId>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <!-- https://mvnrepository.com/artifact/io.dropwizard.metrics/metrics-core -->
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-core</artifactId>
      <version>4.2.30</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/io.dropwizard.metrics/metrics-jvm -->
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-jmx</artifactId>
      <version>4.1.0</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.squareup/javapoet -->
    <dependency>
      <groupId>com.squareup</groupId>
      <artifactId>javapoet</artifactId>
      <version>1.13.0</version>
    </dependency>


    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-launcher</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-testkit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.truth</groupId>
      <artifactId>truth</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

  </dependencies>


  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.pitest</groupId>
          <artifactId>pitest-maven</artifactId>
          <version>1.25.2</version>
          <dependencies>
            <!-- pitest-junit5-plugin 1.2.3 was built against JUnit Platform 1.x;
                 the project runs JUnit Jupiter 6.x. These 1.13.x overrides keep
                 the plugin's discovery happy until pitest-junit5-plugin gains
                 native JUnit 6 support. -->
            <dependency>
              <groupId>org.pitest</groupId>
              <artifactId>pitest-junit5-plugin</artifactId>
              <version>1.2.3</version>
            </dependency>
            <dependency>
              <groupId>org.junit.platform</groupId>
              <artifactId>junit-platform-launcher</artifactId>
              <version>1.13.4</version>
            </dependency>
            <dependency>
              <groupId>org.junit.jupiter</groupId>
              <artifactId>junit-jupiter-engine</artifactId>
              <version>5.13.4</version>
            </dependency>
          </dependencies>
          <configuration>
            <outputFormats>
              <param>HTML</param>
              <param>XML</param>
            </outputFormats>
            <timestampedReports>false</timestampedReports>
            <threads>4</threads>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.6.2</version>
        <executions>
          <execution>
            <id>enforce-maven-wrapper-version</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireMavenVersion>
                  <version>[${maven.version},${maven.version}]</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.15.0</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven.surefire.version}</version>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>license-maven-plugin</artifactId>
        <configuration>
          <skipUpdateLicense>true</skipUpdateLicense>
        </configuration>
      </plugin>
<!--      <plugin>-->
<!--        <groupId>com.mycila</groupId>-->
<!--        <artifactId>license-maven-plugin</artifactId>-->
<!--        <configuration>-->
<!--          <header>com/mycila/maven/plugin/license/templates/EUPL-1.2.txt</header>-->
<!--          <properties>-->
<!--            <owner>Sven Ruppert</owner>-->
<!--            <email>sven.ruppert@gmail.com</email>-->
<!--          </properties>-->
<!--          <excludes>-->
<!--            <exclude>**/*.iml</exclude>-->
<!--            <exclude>**/README*</exclude>-->
<!--            <exclude>**/jacoco.exec*</exclude>-->
<!--            <exclude>**/LICENSE.txt</exclude>-->
<!--            <exclude>**/_data/webdrivers/*</exclude>-->
<!--            &lt;!&ndash;<exclude>src/test/resources/**</exclude>&ndash;&gt;-->
<!--            &lt;!&ndash;<exclude>src/main/resources/**</exclude>&ndash;&gt;-->
<!--            <exclude>**/target/**</exclude>-->
<!--          </excludes>-->
<!--        </configuration>-->
<!--        <executions>-->
<!--          <execution>-->
<!--            <goals>-->
<!--              <goal>check</goal>-->
<!--            </goals>-->
<!--          </execution>-->
<!--        </executions>-->
<!--      </plugin>-->
<!--      <plugin>-->
<!--        <groupId>org.apache.maven.plugins</groupId>-->
<!--        <artifactId>maven-javadoc-plugin</artifactId>-->
<!--        <version>3.1.0</version>-->
<!--        <dependencies>-->
<!--          <dependency>-->
<!--            <groupId>org.ow2.asm</groupId>-->
<!--            <artifactId>asm</artifactId>-->
<!--            <version>7.1</version> &lt;!&ndash; Use newer version of ASM &ndash;&gt;-->
<!--          </dependency>-->
<!--        </dependencies>-->
<!--        <executions>-->
<!--          <execution>-->
<!--            <id>attach-javadocs</id>-->
<!--            <goals>-->
<!--              <goal>jar</goal>-->
<!--            </goals>-->
<!--          </execution>-->
<!--        </executions>-->
<!--        <configuration>-->
<!--          <additionalOptions>-->
<!--&lt;!&ndash;            <failOnError>false</failOnError>&ndash;&gt;-->
<!--&lt;!&ndash;            <additionalOption>-Xdoclint:none</additionalOption>&ndash;&gt;-->
<!--&lt;!&ndash;            <javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>&ndash;&gt;-->
<!--          </additionalOptions>-->
<!--          <destDir>target/doc/apidoc/</destDir>-->
<!--        </configuration>-->
<!--      </plugin>-->
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>release</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>3.3.1</version>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <version>3.11.2</version>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
                <configuration>
                  <doclint>none</doclint>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.2.7</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

  </profiles>

</project>