<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright © 2013 Sven Ruppert (sven.ruppert@gmail.com)

    Licensed under the EUPL-1.2.
    You may obtain a copy of the Licence at:

        https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>com.svenruppert</groupId>
    <artifactId>proxybuilder-parent</artifactId>
    <version>00.11.01</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>proxybuilder-annotations</artifactId>

  <name>Sven Ruppert ProxyBuilder Annotations</name>
  <description>Annotations consumed and emitted by the proxybuilder annotation processor. Tiny, dependency-free module intended for the consumer compile classpath.</description>
  <url>http://www.proxybuilder.org</url>

  <licenses>
    <license>
      <name>European Union Public Licence, Version 1.2</name>
      <url>https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12</url>
      <distribution>repo</distribution>
      <comments>SPDX identifier: EUPL-1.2</comments>
    </license>
  </licenses>

  <scm>
    <url>https://github.com/svenruppert/proxybuilder</url>
    <connection>scm:git:https://github.com/svenruppert/proxybuilder.git</connection>
    <developerConnection>scm:git:https://github.com/svenruppert/proxybuilder.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <developers>
    <developer>
      <name>Sven Ruppert</name>
      <email>sven.ruppert@gmail.com</email>
      <roles>
        <role>Developer</role>
      </roles>
      <timezone>+1</timezone>
    </developer>
  </developers>

  <dependencies>
    <dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-annotations</artifactId>
      <version>4.9.8</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgument>-Xlint:all</compilerArgument>
          <compilerArgument>-proc:none</compilerArgument>
          <showWarnings>true</showWarnings>
          <showDeprecation>true</showDeprecation>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <configuration>
          <targetClasses>
            <param>com.svenruppert.proxybuilder.annotations.*</param>
          </targetClasses>
          <targetTests>
            <param>com.svenruppert.proxybuilder.annotations.*</param>
          </targetTests>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>